### ISSUE TITLE
Re-created ConfigMaps are mistakenly deleted

### ISSUE THREAD

**Issue by ybizeul** [kiwigrid/k8s-sidecar#30] opened 2019-04-27 07:48 UTC
Creating a ConfigMap, deleting it, then re-creating it leads to random deletion of files.

It seems kubernetes has a mechanism that sends a compacted transaction log (see https://github.com/kubernetes-client/python/issues/693). The lack of control in k8s-sidecar leads to deletion of a file that is not wanted.

k8s-sidecar watches for any `DELETED` notification and blindly deletes the attached file without checking that the `DELETED` object is current.

This is causing the following issue : https://github.com/helm/charts/issues/13362

====================================
*Original issue as opened:*

Using this sidecar container in prom-operator (came with it) and trying to understand why my dashboards disappear after a few minutes/hours.

### sidecar environment :
```
    - name: LABEL
      value: grafana_dashboard
    - name: FOLDER
      value: /tmp/dashboards
```

### At the point my dashboards disappeared :

`$FOLDER` Directory is empty :
```
$ k exec -it  prom-grafana-7896944b64-qw52f -c grafana-sc-dashboard bash
I have no name!@prom-grafana-7896944b64-qw52f:/app$ ls -al /tmp/dashboards
total 0
drwxrwsrwx. 2 root  472  6 Apr 26 20:21 .
drwxrwxrwt. 1 root root 24 Apr 26 19:47 ..
```

But ConfigMaps are present :
```
$ k get cm -l grafana_dashboard
NAME                                     DATA   AGE
prom-etcd                                1      21h
prom-k8s-cluster-rsrc-use                1      21h
prom-k8s-coredns                         1      21h
prom-k8s-node-rsrc-use                   1      21h
prom-k8s-resources-cluster               1      21h
prom-k8s-resources-namespace             1      21h
prom-k8s-resources-pod                   1      21h
prom-k8s-resources-workload              1      21h
prom-k8s-resources-workloads-namespace   1      21h
prom-nodes                               1      21h
prom-persistentvolumesusage              1      21h
prom-pods                                1      21h
prom-statefulset                         1      21h
```

Here is the full sidecar log :
```
Starting config map collector
No folder annotation was provided, defaulting to k8s-sidecar-target-directory
Config for cluster api loaded...
Working on configmap monitoring/prom-k8s-resources-pod
Configmap with label found
File in configmap k8s-resources-pod.json ADDED
Working on configmap monitoring/prom-k8s-resources-workloads-namespace
Configmap with label found
File in configmap k8s-resources-workloads-namespace.json ADDED
Working on configmap monitoring/prom-k8s-resources-workload
Configmap with label found
File in configmap k8s-resources-workload.json ADDED
Working on configmap monitoring/prometheus-prom-prometheus-rulefiles-0
Working on configmap monitoring/prom-grafana-datasource
Working on configmap monitoring/prom-grafana-test
Working on configmap monitoring/prom-grafana
Working on configmap monitoring/prom-k8s-cluster-rsrc-use
Configmap with label found
File in configmap k8s-cluster-rsrc-use.json ADDED
Working on configmap monitoring/prom-persistentvolumesusage
Configmap with label found
File in configmap persistentvolumesusage.json ADDED
Working on configmap monitoring/prom-k8s-resources-namespace
Configmap with label found
File in configmap k8s-resources-namespace.json ADDED
Working on configmap monitoring/prom-statefulset
Configmap with label found
File in configmap statefulset.json ADDED
Working on configmap monitoring/prom-k8s-resources-cluster
Configmap with label found
File in configmap k8s-resources-cluster.json ADDED
Working on configmap monitoring/prom-grafana-config-dashboards
Working on configmap monitoring/prom-nodes
Configmap with label found
File in configmap nodes.json ADDED
Working on configmap monitoring/prom-pods
Configmap with label found
File in configmap pods.json ADDED
Working on configmap monitoring/prom-k8s-coredns
Configmap with label found
File in configmap k8s-coredns.json ADDED
Working on configmap monitoring/prom-etcd
Configmap with label found
File in configmap etcd.json ADDED
Working on configmap monitoring/prom-k8s-node-rsrc-use
Configmap with label found
File in configmap k8s-node-rsrc-use.json ADDED
Working on configmap monitoring/prom-k8s-resources-cluster
Configmap with label found
File in configmap k8s-resources-cluster.json ADDED
Working on configmap monitoring/prom-k8s-resources-namespace
Configmap with label found
File in configmap k8s-resources-namespace.json ADDED
Working on configmap monitoring/prom-k8s-resources-pod
Configmap with label found
File in configmap k8s-resources-pod.json ADDED
Working on configmap monitoring/prom-k8s-resources-workload
Configmap with label found
File in configmap k8s-resources-workload.json ADDED
Working on configmap monitoring/prom-k8s-resources-workloads-namespace
Configmap with label found
File in configmap k8s-resources-workloads-namespace.json ADDED
Working on configmap monitoring/prom-nodes
Configmap with label found
File in configmap nodes.json ADDED
Working on configmap monitoring/prom-persistentvolumesusage
Configmap with label found
File in configmap persistentvolumesusage.json ADDED
Working on configmap monitoring/prom-pods
Configmap with label found
File in configmap pods.json ADDED
Working on configmap monitoring/prom-statefulset
Configmap with label found
File in configmap statefulset.json ADDED
Working on configmap monitoring/prometheus-prom-prometheus-rulefiles-0
Working on configmap monitoring/prometheus-prom-prometheus-operator-prometheus-rulefiles-0
Working on configmap monitoring/prometheus-prom-prometheus-operator-prometheus-rulefiles-0
Working on configmap monitoring/prometheus-prom-prometheus-rulefiles-0
Working on configmap monitoring/prometheus-prom-prometheus-rulefiles-0
Working on configmap monitoring/prom-prometheus-operator-grafana-datasource
Working on configmap monitoring/prom-prometheus-operator-etcd
Configmap with label found
File in configmap etcd.json DELETED
Working on configmap monitoring/prom-prometheus-operator-k8s-cluster-rsrc-use
Configmap with label found
File in configmap k8s-cluster-rsrc-use.json DELETED
Working on configmap monitoring/prometheus-prom-prometheus-operator-prometheus-rulefiles-0
Working on configmap monitoring/prom-prometheus-operator-k8s-coredns
Configmap with label found
File in configmap k8s-coredns.json DELETED
Working on configmap monitoring/prometheus-prom-prometheus-operator-prometheus-rulefiles-0
Working on configmap monitoring/prom-prometheus-operator-k8s-node-rsrc-use
Configmap with label found
File in configmap k8s-node-rsrc-use.json DELETED
Working on configmap monitoring/prom-prometheus-operator-k8s-resources-cluster
Configmap with label found
File in configmap k8s-resources-cluster.json DELETED
Working on configmap monitoring/prom-prometheus-operator-k8s-resources-namespace
Configmap with label found
File in configmap k8s-resources-namespace.json DELETED
Working on configmap monitoring/prom-prometheus-operator-k8s-resources-pod
Configmap with label found
File in configmap k8s-resources-pod.json DELETED
Working on configmap monitoring/prom-prometheus-operator-k8s-resources-workload
Configmap with label found
File in configmap k8s-resources-workload.json DELETED
Working on configmap monitoring/prom-prometheus-operator-k8s-resources-workloads-namespace
Configmap with label found
File in configmap k8s-resources-workloads-namespace.json DELETED
Working on configmap monitoring/prom-prometheus-operator-nodes
Configmap with label found
File in configmap nodes.json DELETED
Working on configmap monitoring/prom-prometheus-operator-persistentvolumesusage
Configmap with label found
File in configmap persistentvolumesusage.json DELETED
Working on configmap monitoring/prom-prometheus-operator-pods
Configmap with label found
File in configmap pods.json DELETED
Working on configmap monitoring/prom-prometheus-operator-statefulset
Configmap with label found
File in configmap statefulset.json DELETED
Working on configmap monitoring/prometheus-prom-prometheus-rulefiles-0
Working on configmap monitoring/prometheus-prom-prometheus-operator-prometheus-rulefiles-0
Working on configmap monitoring/prometheus-prom-prometheus-rulefiles-0
```

Note that some of the ConfigMaps mentioned I can't even find, not sure it's related.

The reason I open this issue is that in the end, I do have ConfigMaps with that label and they are not present in the directory.

**Comment by ybizeul** [comment] 2019-04-27 09:33
Possibly catch something unexpected while watching the logs :
```
Apr 27 10:54:48 ApiException when calling kubernetes: (500)
Apr 27 10:54:48 Reason: Internal Server Error
Apr 27 10:54:48 HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Sat, 27 Apr 2019 08:54:50 GMT', 'Content-Length': '186'})
Apr 27 10:54:48 HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"resourceVersion: Invalid value: \\"None\\": strconv.ParseUint: parsing \\"None\\": invalid syntax","code":500}\n'
Apr 27 10:54:48 
Apr 27 10:54:48 
Apr 27 10:54:48 Working on configmap monitoring/prom-k8s-resources-pod
Apr 27 10:54:48 Configmap with label found
Apr 27 10:54:48 File in configmap k8s-resources-pod.json ADDED
Apr 27 10:54:48 Working on configmap monitoring/prom-k8s-resources-workloads-namespace
Apr 27 10:54:48 Configmap with label found
Apr 27 10:54:48 File in configmap k8s-resources-workloads-namespace.json ADDED
Apr 27 10:54:48 Working on configmap monitoring/prometheus-prom-prometheus-rulefiles-0
Apr 27 10:54:48 Working on configmap monitoring/prom-k8s-resources-workload
Apr 27 10:54:48 Configmap with label found
Apr 27 10:54:48 File in configmap k8s-resources-workload.json ADDED
Apr 27 10:54:48 Working on configmap monitoring/prom-grafana-datasource
Apr 27 10:54:48 Working on configmap monitoring/prom-grafana-test
Apr 27 10:54:48 Working on configmap monitoring/prom-grafana
Apr 27 10:54:48 Working on configmap monitoring/prom-k8s-cluster-rsrc-use
Apr 27 10:54:48 Configmap with label found
Apr 27 10:54:48 File in configmap k8s-cluster-rsrc-use.json ADDED
Apr 27 10:54:48 Working on configmap monitoring/prom-k8s-resources-namespace
Apr 27 10:54:48 Configmap with label found
Apr 27 10:54:48 File in configmap k8s-resources-namespace.json ADDED
Apr 27 10:54:48 Working on configmap monitoring/prom-persistentvolumesusage
Apr 27 10:54:48 Configmap with label found
Apr 27 10:54:48 File in configmap persistentvolumesusage.json ADDED
Apr 27 10:54:48 Working on configmap monitoring/prom-statefulset
Apr 27 10:54:48 Configmap with label found
Apr 27 10:54:48 File in configmap statefulset.json ADDED
Apr 27 10:54:48 Working on configmap monitoring/prom-grafana-config-dashboards
Apr 27 10:54:48 Working on configmap monitoring/prom-k8s-resources-cluster
Apr 27 10:54:48 Configmap with label found
Apr 27 10:54:48 File in configmap k8s-resources-cluster.json ADDED
Apr 27 10:54:48 Working on configmap monitoring/prom-nodes
Apr 27 10:54:48 Configmap with label found
Apr 27 10:54:48 File in configmap nodes.json ADDED
Apr 27 10:54:48 Working on configmap monitoring/prom-pods
Apr 27 10:54:48 Configmap with label found
Apr 27 10:54:48 File in configmap pods.json ADDED
Apr 27 10:54:48 Working on configmap monitoring/prom-k8s-coredns
Apr 27 10:54:48 Configmap with label found
Apr 27 10:54:48 File in configmap k8s-coredns.json ADDED
Apr 27 10:54:48 Working on configmap monitoring/prom-etcd
Apr 27 10:54:48 Configmap with label found
Apr 27 10:54:48 File in configmap etcd.json ADDED
Apr 27 10:54:48 Working on configmap monitoring/prom-k8s-node-rsrc-use
Apr 27 10:54:48 Configmap with label found
Apr 27 10:54:48 File in configmap k8s-node-rsrc-use.json ADDED
Apr 27 11:28:33 Working on configmap monitoring/prom-k8s-resources-cluster
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap k8s-resources-cluster.json ADDED
Apr 27 11:28:33 Working on configmap monitoring/prom-k8s-resources-namespace
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap k8s-resources-namespace.json ADDED
Apr 27 11:28:33 Working on configmap monitoring/prom-k8s-resources-pod
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap k8s-resources-pod.json ADDED
Apr 27 11:28:33 Working on configmap monitoring/prom-k8s-resources-workload
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap k8s-resources-workload.json ADDED
Apr 27 11:28:33 Working on configmap monitoring/prom-k8s-resources-workloads-namespace
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap k8s-resources-workloads-namespace.json ADDED
Apr 27 11:28:33 Working on configmap monitoring/prom-nodes
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap nodes.json ADDED
Apr 27 11:28:33 Working on configmap monitoring/prom-persistentvolumesusage
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap persistentvolumesusage.json ADDED
Apr 27 11:28:33 Working on configmap monitoring/prom-pods
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap pods.json ADDED
Apr 27 11:28:33 Working on configmap monitoring/prom-statefulset
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap statefulset.json ADDED
Apr 27 11:28:33 Working on configmap monitoring/prometheus-prom-prometheus-rulefiles-0
Apr 27 11:28:33 Working on configmap monitoring/prometheus-prom-prometheus-operator-prometheus-rulefiles-0
Apr 27 11:28:33 Working on configmap monitoring/prometheus-prom-prometheus-operator-prometheus-rulefiles-0
Apr 27 11:28:33 Working on configmap monitoring/prometheus-prom-prometheus-rulefiles-0
Apr 27 11:28:33 Working on configmap monitoring/prometheus-prom-prometheus-rulefiles-0
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-grafana-datasource
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-etcd
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap etcd.json DELETED
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-k8s-cluster-rsrc-use
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap k8s-cluster-rsrc-use.json DELETED
Apr 27 11:28:33 Working on configmap monitoring/prometheus-prom-prometheus-operator-prometheus-rulefiles-0
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-k8s-coredns
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap k8s-coredns.json DELETED
Apr 27 11:28:33 Working on configmap monitoring/prometheus-prom-prometheus-operator-prometheus-rulefiles-0
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-k8s-node-rsrc-use
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap k8s-node-rsrc-use.json DELETED
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-k8s-resources-cluster
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap k8s-resources-cluster.json DELETED
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-k8s-resources-namespace
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap k8s-resources-namespace.json DELETED
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-k8s-resources-pod
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap k8s-resources-pod.json DELETED
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-k8s-resources-workload
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap k8s-resources-workload.json DELETED
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-k8s-resources-workloads-namespace
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap k8s-resources-workloads-namespace.json DELETED
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-nodes
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap nodes.json DELETED
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-persistentvolumesusage
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap persistentvolumesusage.json DELETED
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-pods
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap pods.json DELETED
Apr 27 11:28:33 Working on configmap monitoring/prom-prometheus-operator-statefulset
Apr 27 11:28:33 Configmap with label found
Apr 27 11:28:33 File in configmap statefulset.json DELETED
Apr 27 11:28:33 Working on configmap monitoring/prometheus-prom-prometheus-rulefiles-0
Apr 27 11:28:33 Working on configmap monitoring/prometheus-prom-prometheus-operator-prometheus-rulefiles-0
Apr 27 11:28:33 Working on configmap monitoring/prometheus-prom-prometheus-rulefiles-0
```

**Comment by ybizeul** [comment] 2019-04-28 07:07
I just catch the full `DELETE` event, it seems kubernetes mistakenly notifies this, as the resource is still there in the ConfigMap : (note that there is no `deletion_timestamp`)
```
Event: DELETED {'annotations': None,
 'cluster_name': None,
 'creation_timestamp': datetime.datetime(2019, 4, 25, 7, 41, 15, tzinfo=tzutc()),
 'deletion_grace_period_seconds': None,
 'deletion_timestamp': None,
 'finalizers': None,
 'generate_name': None,
 'generation': None,
 'initializers': None,
 'labels': {u'app': 'prometheus-operator-grafana',
            u'chart': 'prometheus-operator-5.2.0',
            u'grafana_dashboard': '1',
            u'heritage': 'Tiller',
            u'release': 'prom'},
 'name': 'prom-prometheus-operator-etcd',
 'namespace': 'monitoring',
 'owner_references': None,
 'resource_version': '2677444',
 'self_link': '/api/v1/namespaces/monitoring/configmaps/prom-prometheus-operator-etcd',
 'uid': '8174ae9d-672d-11e9-9c4b-0050568956e9'}
```

**Comment by Tim-Smyth** [comment] 2019-05-13 07:42
Hi Yann,
That error didn't happen to us yet, interesting. Do you know what happened at Apr 27 11:28:33? Helm upgrade?
The current implementation assumes that the kubernetes client returns the events in the order of occurrence, so I will have to check further if maybe ignoring a Delete event without deletion timestamp is a valid workaround.

**Comment by Tim-Smyth** [comment] 2019-07-08 11:02
Closing for now since we were not able to reproduce the problem. Please reopen when the problem occurred again

**Closed by Tim-Smyth** 2019-07-08 11:02 UTC
